version: '3'

services:
  db:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: 
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
      replicas: 1
      restart_policy:
        condition: on-failure
